# إعدادات JVM لعملية البناء
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# تفعيل AndroidX (إلزامي للمشاريع الحديثة)
android.useAndroidX=true
android.nonTransitiveRClass=true

# استخدام Kotlin الرسمي لـ code style
kotlin.code.style=official

# السماح باستخدام compileSdk=35 مع AGP 8.5.2 (لسه متجرّبش رسميًا عليها لحد الإصدار ده)
android.suppressUnsupportedCompileSdk=35
